language: scala
scala:
  - 2.12.0-M3
  - 2.11.8
jdk:
  - oraclejdk8
matrix:
  fast_finish: true
  allow_failures:
    - scala: 2.12.0-M3
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - tmp/
script:
  - sbt ++$TRAVIS_SCALA_VERSION compile
  - sbt ++$TRAVIS_SCALA_VERSION test
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm